\documentclass{scrartcl}
%\usepackage[ngerman]{babel}
\usepackage[margin=2cm, includefoot]{geometry}
<<init, echo = FALSE>>=
pacman::p_load(fs)
init_file <- file.path(path_home(), "Documents/GitHub/project/init")
@

\input{\Sexpr{init_file}}

% -----------------------------------------------------------------------
\begin{document}
\maketitle

<<naming, echo = FALSE>>=
## libraries
pacman::p_load(tidyverse, simstudy, knitr, plyr, readxl, magrittr, stringi,
               missRanger)
student_name <- "templateName"
student_file <- str_replace_all(str_replace(student_name, ", ", "_"), " ", "_")
student_out_file <- file.path(path_home(), "Documents/GitHub/project/template/tmp", str_c(student_file, ".csv"))
student_out_basename_file <- str_c("data_", basename(student_out_file))
## back to umlaute
student_name %<>% stri_replace_all_fixed(c("ae", "oe", "ue", "Ae", "Oe", "Ue"), 
                                         c("{\"a}", "{\"o}", "{\"u}", "{\"A}", "{\"O}", "{\"U}"), 
                                         vectorize_all = FALSE)

@

\section*{Name, Vorname: \Sexpr{student_name}}


<<intro, echo = FALSE>>=

location_vec <- c("field", "chamber")  %>% sample(1)

field_coords <- c("52.318123, 8.102339", "52.319599, 8.049495",
                  "52.325898, 7.983396", "52.257219, 8.155912") %>% sample(1)

chamber_file <- c("log.series.000.1124.1.txt", "log.series.zhzt.11022.txt") %>% sample(1)

text_vec <- lst(field = c(str_c("Sie führen ein Feldexperiment mit einer landwirtschaftlich bedeutenden Pflanze durch. Das Feld befindet sich unter den Koordinaten ", field_coords, " in der Nähe von Osnabrück. Das war das beste Feld was Sie für Ihren Versuch kriegen konnten. Nehmen Sie dieses Feld als Ausgangspunkt für Ihre Versuchsplanung. Beachten Sie eventuelle Einflüsse durch die Umwelt anhand der Koordinaten in Ihrer Einleitung und Diskussion.")),
                chamber = c(str_c("Sie führen ein Gewächshausexperiment mit einer gartenbaulich bedeutenden Pflanze durch. Sie haben insgesamt vier Tische in dem Gewächshaus zu Verfügung. Auf die Tische passen bis zu sechzig Töpfe. Ihnen Stand eine automatische Klimasteuerung zu Verfügung der Sie blind vertraut haben. Mit der Datei \\texttt{", chamber_file, "} wurde Ihnen am Ende des Versuches noch der Status der Anlage zur Klimasteuerung während des Versuches mitgeteilt. Berücksichtigen Sie Informationen in Ihrer Diskussion."))) %>%
  pluck(location_vec)

if(location_vec == "chamber"){
  invisible(file.copy(file.path(path_home(), "Documents/GitHub/project/template", chamber_file),
            file.path(path_home(), "Documents/GitHub/project/template/tmp", str_c(student_file, "_", chamber_file))))
}

endpoint <- c("drymatter", "greenfly", "infected") %>% sample(1)

species <- c("Basilikum", "Raps", "Sellerie", "Wasserlinsen",
             "Agaven", "Bananen", "Vanille", "Pfeffer", "Nelken",
             "Tonkabohnen", "Birnen", "Kartoffeln",
             "Grünkohl", "Mais", "Muskatnuss", "Zuckerrohr",
             "Oregano", "Mandarinen", "Papaya", "Wassermelone",
             "Mango", "Durian", "Götterbaum") %>% sample(1)



@ 


<<data, echo = FALSE, results='hide'>>=

n_trt <- c(3, 4) %>% sample(1)
n_block <- c(3, 4) %>% sample(1)
n_rep <- c(3, 4, 5) %>% sample(1)

block_str <- c("I", "II", "III", "IV")
trt_str <- c("A", "B", "C", "D")

data_tbl <- expand_grid(trt = 1:n_trt, block = 1:n_block, rep = 1:n_rep) %>% 
  dplyr::mutate(water = round(rnorm(n(), 20, 5), 2),
                N = round(rnorm(n(), 5, 1), 2),
                drymatter = round(20 + 1.2 * trt + 0.6 * block - 0.05 * water + 0.07 * N + rnorm(n(), 0, 1), 2),
                greenfly = round(10 - 1.5 * trt + 0.6 * block + 0.05 * water - 0.09 * N + rpois(n(), 4)),
                infected = round(20 + 1.5 * trt + 0.5 * block - 0.2 * water + 1.1 * N + rnorm(n(), 0, 1), 2),
                greenfly = ifelse(greenfly <= 2, 0, greenfly),
                infected = ifelse(infected <= 25, 0, 1),
                trt = factor(trt, labels = trt_str[1:n_trt]),
                block = factor(block, labels = block_str[1:n_block])) %>% 
  select(-rep) %>% 
  generateNA(p = c(0, 0, 0.05, 0.1, 0, 0, 0))

## data writing
write_csv2(data_tbl, student_out_file)
@


\textit{\Sexpr{text_vec}}

\vspace{1Ex}

Im Folgenden ist ein Ausschnitt aus der Datentabelle gegeben.

\vspace{1Ex}

\begin{center}
<<print, echo = FALSE>>=
data_tbl %>% head(n = 9) %>% kable(align = "c", "latex",
  booktabs = TRUE, position = "h")
@
\end{center}

\vspace{1Ex}

Sie finden die vollst{\"a}ndigen Daten in der Datei
\verb|\Sexpr{student_out_basename_file}|. Laden Sie die vollst{\"a}ndigen Daten
in R und rechnen Sie auf den vollst{\"a}ndigen Daten Ihre Analysen.


\subsection*{Formalia}

\subsubsection*{... f{\"u}r den Bericht}

\begin{enumerate}
\item Die Datenanalyse in R und die Erstellung des Berichts findet in
  \textit{Quatro} statt. 
\item Ihr Bericht folgt dem IMRaD Schema und ist acht bis
  \textbf{maximal} zehn Seiten lang.
\item Ihr Bericht beinhaltet zwischen f{\"u}nf und zehn wissenschaftliche
  Referenzen. \textit{Als Referenzen z{\"a}hlen ausdr{\"u}cklich nicht die genutzen
    R Pakete oder etwaige Internetseiten.}
\end{enumerate}

\subsubsection*{... f{\"u}r die Pr{\"a}sentation}

\begin{enumerate}
\item Sie stellen in Ihrer Pr{\"a}sentation Ihre selbst erdachte Fragestellung
  und die Ergebnisse Ihrer Datananalyse in R vor.
\item Ihre Pr{\"a}sentation der Datenanalyse in R ist maximal 10 Folien lang.
\item[Oder] Sie stellen in Ihrer Pr{\"a}sentation Ihre selbst erstellte R Shiny Web
  App vor. 
\end{enumerate}

\subsection*{Datenanalyse in R}

In Ihrer Analyse ist der Endpunkt $y$ die Spalte
\textbf{\Sexpr{endpoint}}. Ihre zu untersuchende Pflanze ist/sind
\Sexpr{species}. Diese Festlegung des Endpunktes auf
\textbf{\Sexpr{endpoint}} und der zu untersuchenden Pflanze \Sexpr{species} ist f{\"u}r die
folgenden Aufgabenteile bindend.

\begin{enumerate}
\item Entwickeln Sie anhand der vorliegenden Daten eine Fragestellung!
\item Nutzen Sie das Tool \texttt{ChatGPT} um die Einleitung zu
  schreiben. Geben Sie am Ende der Einleitung eine tabellarische {\"U}bersicht
  der Fragen an \texttt{ChatGPT}!
\item Zeichen Sie mit den gegebenen Informationen den Versuchsplan. Welche
  Annahmen haben Sie getroffen? Erl{\"a}utern Sie Ihr Vorgehen.
\item Visualisieren Sie Ihre Daten in \texttt{ggplot} im Kontext der
  Fragestellung!
\item Rechen Sie die statistische Analyse in R entsprechend Ihres
  Endpunktes \textbf{\Sexpr{endpoint}}! Beachten Sie dabei folgende Fragen.
  \begin{enumerate}
  \item Liegen in Ihren Daten Ausrei{\ss}er vor? Wie gehen Sie mit potenziellen
    Ausrei{\ss}ern um? Erl{\"a}utern Sie Ihr Vorgehen!
  \item Liegen in Ihren Daten fehlende Beobachtungen vor? Wie gehen Sie mit
    den fehlenden Daten um? Erl{\"a}utern Sie Ihr Vorgehen!
  \item Rechen Sie einen multiplen Gruppenvergleich! Gehen Sie dabei auch
    auf die Adjustierung f{\"u}r multiple Vergleiche ein. Begr{\"u}nden Sie Ihr
    Vorgehen!
  \item Berichten Sie die Effekte der Behandlung im Kontext der
    Fragestellung!
  \item Visualisieren Sie die Ergebnisse des multiplen Vergleiches!
    Begr{\"u}nden Sie Ihr Vorgehen!
  \end{enumerate}
\item Diskutieren Sie Ihre Ergebnisse im Kontext der Fragestellung und
  m{\"o}glicher Komplikationen! Nutzen Sie auch hier das Tool
  \texttt{ChatGPT}. Geben Sie am Ende der Diskussion eine tabellarische
  {\"U}bersicht der Fragen an \texttt{ChatGPT}!
\end{enumerate}

\subsection*{R Shiny Web App}

Besuchen Sie die Internetseite https://ourworldindata.org/ und laden sich
einen Datensatz von Ihrem Interesse runter. Sie d{\"u}rfen den Datensatz
beliebig vorab k{\"u}rzen oder bearbeiten, so dass Sie die Aufgabe gut l{\"o}sen k{\"o}nnen.

\begin{enumerate}
\item {\"U}berlegen Sie sich eine Fragestellung zu den Daten.
\item Erstellen Sie eine R Shiny Web App aus den Daten, die bei der
  Beantwortung der Fragestellung hilfreich ist.
\item Sie geben die R Shiny Web App als ZIP-Datei ab. Die ZIP-Datei beinhaltend alle
  notwendigen Dateien um die App laufen zu lassen. 
\end{enumerate}

\subsection*{Zerforschung I}

Suchen Sie sich auf dem Campus Haste ein wissenschaftliches Poster und
Fotografieren Sie eine der dortigen statistischen Abbildungen!

\begin{enumerate}
\item Erstellen Sie den Datensatz auf dem die Abbildung basieren k{\"o}nnte!
  Sch{\"a}tzen Sie daf{\"u}r grob die Zahlen aus der fotografierten Abbildung ab.
\item Bauen Sie aus den selbst erstellten Daten die fotografierte Abbildung in
  \texttt{ggplot()} nach! 
\item Geben Sie den Code und die Abbildung in einem R Quarto erstellten
  Dokument ab!
\end{enumerate}

\subsection*{Zerforschung II}

Begeben Sie sich in die Bibliothek in Haste. Suchen Sie sich drei
Abschlussarbeiten aus. Wir konzentrieren uns hier auf die Bachelorarbeit.

\begin{enumerate}
\item Erstellen Sie eine deskriptive {\"U}bersicht {\"u}ber den Umfang der drei
  Abschlussarbeiten!
\item \textit{Sehen Sie folgende Fragen als Inspiration.} Wie viele Referenzen
  finden Sie? Welche Art sind die Referenzen? Wie lang ist die Einleitung?
  Wie viele Abschnitte haben die einzelnen Teile? Welche statistischen
  Tests werden verwendet? Welche Abschnitte gibt es {\"u}berhaupt? Wie viele
  Referenzen stammen von dem Betreuenden?
\item Fassen Sie Ihre {\"U}bersicht in maximal drei Seiten zusammen.
\end{enumerate}

\subsection*{Zerforschung III}

W{\"a}hlen Sie eine Kurzbeschreibung eines Forschungsvorhaben aus der Datei
\textit{Forschungsideen.pdf} aus.

\begin{enumerate}
\item Erstellen Sie eine Exceldatei entsprechend der Kurzbeschreibung! Sie
  wollen nach dem Versuch die erstellte Exceldatei dann mit den Messdaten f{\"u}llen.
  Beachten Sie, dass Sie Wiederholungen ben{\"o}tigen. Legen Sie die Anzahl an
  Wiederholungen selbstst{\"a}ndig fest. Die Exceldatei muss in R einlesbar sein.
\item Erstellen Sie eine Randomisierung und Visualisierung des experimentellen
  Versuchsdesign anhand der Kurzbeschreibung! Sie k{\"o}nnen die Randomisierung
  in PowerPoint oder \textit{desplot} visualisieren.
\end{enumerate}

\subsection*{Erforschen \& Erkunden}

Besuchen Sie den Hasefriedhof \textit{oder} den Johannisfriedhof in
Osnabr{\"u}ck. Finden Sie eine Pers{\"o}nlichkeit, die dort ruht und Sie
inspiriert. Die Pers{\"o}nlichkeit sollte im weitesten Sinne eine Verbindung zur
Wissenschaft haben. Anfang des letzten Jahrhunderts ist die Trennung der
Disziplinen aber sehr unscharf.

\begin{enumerate}
\item Machen Sie ein aussagekr{\"a}ftiges Foto von der Grabst{\"a}tte!
\item F{\"u}gen Sie das Foto in ein Dokument ein und schreiben Sie ein bis zwei
  Seiten {\"u}ber die Pers{\"o}nlichkeit und deren wissenschaftliches Wirken!
\item Warum haben Sie diese Pers{\"o}nlichkeit gew{\"a}hlt? Was hat Sie inspiriert?
\end{enumerate}

\subsection*{Reflexion}

Besuchen Sie die Internetseite https://www.bigbookofr.com/ und w{\"a}hlen Sie
eines der {\"u}ber 300 B{\"u}cher aus. Sie d{\"u}rfen jedes Thema nehmen was Sie
interessiert. Nehmen Sie aber ein \textit{Buch}, keine verlinkte
Internetseite oder Blogartikel.

\begin{enumerate}
\item Schreiben Sie eine maximal zweiseitige Zusammenfassung {\"u}ber das Buch!
\item Warum haben Sie dieses Buch gewählt?
\end{enumerate}

\subsection*{Benotung}

Im Folgenden ist die Tabelle für die Benotung angegeben. Es können maximal 23 Punkte erreicht werden. Um das Modul zu bestehen benötigen Sie mindestens 12 Punkte. Themen mit Teilpunkten, die in \textcolor{red}{rot} gedruckt sind, müssen \textbf{mindestens} erreicht werden.

\begin{center}
  \begin{tabular}{lll}
    \toprule
    Thema & Teilpunkte & Punkte\\
    \midrule
    Datenanalyse in R & 0, \textcolor{red}{1}, 2, 3, 4 &  \\[1Ex]
    R Shiny Web App & 0, 1, 2, 3, 4  & \\[1Ex]
    Pr{\"a}sentation & 0, 1  & \\[1Ex]
    Zerforschung I & 0, \textcolor{red}{1}, 2, 3, 4  & \\[1Ex]
    Zerforschung II & 0, \textcolor{red}{1}, 2  & \\[1Ex]
    Zerforschung III & 0, \textcolor{red}{1}, 2, 3, 4  & \\[1Ex]
    Erforschen \& Erkunden & 0, 1, 2 & \\[1Ex]
    Reflexion & 0, 1, 2 & \\
    \midrule
    & Summe & \\
    \bottomrule
  \end{tabular}
\end{center}

\subsubsection*{Die Abgabe des Portfolios ist - digital oder als Ausdruck - jederzeit möglich, spätestens zum 31. Januar 2024.}

\end{document}
