\documentclass{scrartcl}
%\usepackage[ngerman]{babel}
\usepackage[margin=2cm, includefoot]{geometry}
<<init, echo = FALSE>>=
pacman::p_load(fs)
init_file <- file.path(path_home(), "Documents/GitHub/project/init")
@

\input{\Sexpr{init_file}}

% -----------------------------------------------------------------------
\begin{document}
\maketitle

<<naming, echo = FALSE>>=
## libraries
pacman::p_load(tidyverse, simstudy, knitr, plyr, readxl, magrittr, stringi,
               missRanger)
student_name <- "templateName"
student_file <- str_replace_all(str_replace(student_name, ", ", "_"), " ", "_")
student_out_file <- file.path(path_home(), "Documents/GitHub/project/template/tmp", str_c(student_file, ".csv"))
student_out_basename_file <- str_c("data_", basename(student_out_file))
## back to umlaute
student_name %<>% stri_replace_all_fixed(c("ae", "oe", "ue", "Ae", "Oe", "Ue"), 
                                         c("{\"a}", "{\"o}", "{\"u}", "{\"A}", "{\"O}", "{\"U}"), 
                                         vectorize_all = FALSE)

@

\section*{Portfoliopr{\"u}fung von Name, Vorname: \Sexpr{student_name}}



<<intro, echo = FALSE>>=

location_vec <- c("field", "chamber")  %>% sample(1)

field_coords <- c("52.318123, 8.102339", "52.319599, 8.049495",
                  "52.325898, 7.983396", "52.257219, 8.155912") %>% sample(1)

chamber_file <- c("log.series.000.1124.1.txt", "log.series.zhzt.11022.txt") %>% sample(1)

text_vec <- lst(field = c(str_c("Sie f{\"u}hren ein Feldexperiment mit einer landwirtschaftlich bedeutenden Pflanze durch. Das Feld befindet sich unter den Koordinaten ", field_coords, " in der N{\"a}he von Osnabr{\"u}ck. Das war das beste Feld was Sie f{\"u}r Ihren Versuch kriegen konnten. Nehmen Sie dieses Feld als Ausgangspunkt f{\"u}r Ihre Versuchsplanung. Beachten Sie eventuelle Einfl{\"u}sse durch die Umwelt anhand der Koordinaten in Ihrer Einleitung und Diskussion.")),
                chamber = c(str_c("Sie f{\"u}hren ein Gew{\"a}chshausexperiment mit einer gartenbaulich bedeutenden Pflanze durch. Sie haben insgesamt vier Tische in dem Gew{\"a}chshaus zu Verf{\"u}gung. Auf die Tische passen bis zu sechzig T{\"o}pfe. Ihnen Stand eine automatische Klimasteuerung zu Verf{\"u}gung der Sie blind vertraut haben. Mit der Datei \\texttt{", chamber_file, "} wurde Ihnen am Ende des Versuches noch der Status der Anlage zur Klimasteuerung w{\"a}hrend des Versuches mitgeteilt. Ber{\"u}cksichtigen Sie Informationen in Ihrer Diskussion."))) %>%
  pluck(location_vec)

if(location_vec == "chamber"){
  invisible(file.copy(file.path(path_home(), "Documents/GitHub/project/template", chamber_file),
            file.path(path_home(), "Documents/GitHub/project/template/tmp", str_c(student_file, "_", chamber_file))))
}

endpoint <- c("drymatter", "greenfly", "infected") %>% sample(1)

species <- c("Basilikum", "Raps", "Sellerie", "Wasserlinsen",
             "Agaven", "Bananen", "Vanille", "Pfeffer", "Nelken",
             "Tonkabohnen", "{\"A}pfel", "Birnen", "Kartoffeln",
             "Gr{\"u}nkohl", "Mais", "Muskatnuss", "Zuckerrohr",
             "Oregano", "Mandarinen", "Papaya", "Wassermelone",
             "Mango", "Durian", "G{\"o}tterbaum") %>% sample(1)



@ 


<<data, echo = FALSE, results='hide'>>=

n_trt <- c(3, 4) %>% sample(1)
n_block <- c(3, 4) %>% sample(1)
n_rep <- c(3, 4, 5) %>% sample(1)

block_str <- c("I", "II", "III", "IV")
trt_str <- c("A", "B", "C", "D")

data_tbl <- expand_grid(trt = 1:n_trt, block = 1:n_block, rep = 1:n_rep) %>% 
  dplyr::mutate(water = round(rnorm(n(), 20, 5), 2),
                N = round(rnorm(n(), 5, 1), 2),
                drymatter = round(20 + 1.2 * trt + 0.6 * block - 0.05 * water + 0.07 * N + rnorm(n(), 0, 1), 2),
                greenfly = round(10 - 1.5 * trt + 0.6 * block + 0.05 * water - 0.09 * N + rpois(n(), 4)),
                infected = round(20 + 1.5 * trt + 0.5 * block - 0.2 * water + 1.1 * N + rnorm(n(), 0, 1), 2),
                greenfly = ifelse(greenfly <= 2, 0, greenfly),
                infected = ifelse(infected <= 25, 0, 1),
                trt = factor(trt, labels = trt_str[1:n_trt]),
                block = factor(block, labels = block_str[1:n_block])) %>% 
  select(-rep) %>% 
  generateNA(p = c(0, 0, 0.05, 0.1, 0, 0, 0))

## data writing
write_csv2(data_tbl, student_out_file)
@


\textit{\Sexpr{text_vec}}

\vspace{1Ex}

Im Folgenden ist ein Ausschnitt aus der Datentabelle gegeben.

\vspace{1Ex}

\begin{center}
<<print, echo = FALSE>>=
data_tbl %>% head(n = 9) %>% kable(align = "c", "latex",
  booktabs = TRUE, position = "h")
@
\end{center}

\vspace{1Ex}

Sie finden die vollst{\"a}ndigen Daten in der Datei \verb|\Sexpr{student_out_basename_file}|. Laden Sie die vollst{\"a}ndigen Daten in R und rechnen Sie auf den vollst{\"a}ndigen Daten Ihre Analysen.


\subsection*{Formalia}

\subsubsection*{... f{\"u}r den Bericht}

\begin{enumerate}
\item Die Datenanalyse in R und die Erstellung des Berichts findet in
  \textit{Quatro} statt. 
\item Ihr Bericht folgt dem IMRaD Schema und ist acht bis
  \textbf{maximal} zehn Seiten lang.
\item Ihr Bericht beinhaltet zwischen f{\"u}nf und zehn wissenschaftliche
  Referenzen. \textit{Als Referenzen z{\"a}hlen ausdr{\"u}cklich nicht die genutzen
    R Pakete oder etwaige Internetseiten.}
\end{enumerate}

\subsubsection*{... f{\"u}r die Pr{\"a}sentation}

\begin{enumerate}
\item Sie stellen in Ihrer Pr{\"a}sentation Ihre selbst erdachte Fragestellung
  und die Ergebnisse Ihrer Datananalyse in R vor.
\item Ihre Pr{\"a}sentation der Datenanalyse in R ist maximal 10 Folien lang.
\item Sie stellen in Ihrer Pr{\"a}sentation Ihre selbst erstellte R Shiny Web
  App vor. 
\end{enumerate}

\subsection*{Datenanlyse in R}

In Ihrer Analyse ist der Endpunkt $y$ die Spalte
\textbf{\Sexpr{endpoint}}. Ihre zu untersuchende Pflanze ist/sind
"`\Sexpr{species}"'. Diese Festlegung des Endpunktes auf
\textbf{\Sexpr{endpoint}} und der zu untersuchenden Pflanze "`\Sexpr{species}"' ist f{\"u}r die
folgenden Aufgabenteile bindend.

\begin{enumerate}
\item Entwickeln Sie anhand der vorliegenden Daten eine Fragestellung!
\item Nutzen Sie das Tool \texttt{ChatGPT} um die Einleitung zu
  schreiben. Geben Sie am Ende der Einleitung eine tabellarische {\"U}bersicht
  der Fragen an \texttt{ChatGPT}!
\item Zeichen Sie mit den gegebenen Informationen den Versuchsplan. Welche
  Annahmen haben Sie getroffen? Erl{\"a}utern Sie Ihr Vorgehen.
\item Visualisieren Sie Ihre Daten in \texttt{ggplot} im Kontext der
  Fragestellung!
\item Rechen Sie die statistische Analyse in R entsprechend Ihres
  Endpunktes \textbf{\Sexpr{endpoint}}! Beachten Sie dabei folgende Fragen.
  \begin{enumerate}
  \item Liegen in Ihren Daten Ausrei{\ss}er vor? Wie gehen Sie mit potenziellen
    Ausrei{\ss}ern um? Erl{\"a}utern Sie Ihr Vorgehen!
  \item Liegen in Ihren Daten fehlende Beobachtungen vor? Wie gehen Sie mit
    den fehlenden Daten um? Erl{\"a}utern Sie Ihr Vorgehen!
  \item Rechen Sie einen multiplen Gruppenvergleich! Gehen Sie dabei auch
    auf die Adjustierung f{\"u}r multiple Vergleiche ein. Begr{\"u}nden Sie Ihr
    Vorgehen!
  \item Berichten Sie die Effekte der Behandlung im Kontext der
    Fragestellung!
  \item Visualisieren Sie die Ergebnisse des multiplen Vergleiches!
    Begr{\"u}nden Sie Ihr Vorgehen!
  \end{enumerate}
\item Diskutieren Sie Ihre Ergebnisse im Kontext der Fragestellung und
  m{\"o}glicher Komplikationen! Nutzen Sie auch hier das Tool
  \texttt{ChatGPT}. Geben Sie am Ende der Diskussion eine tabellarische
  {\"U}bersicht der Fragen an \texttt{ChatGPT}!
\end{enumerate}

\subsection*{R Shiny Web App}

Besuchen Sie die Internetseite https://ourworldindata.org/ und laden sich
einen Datensatz von Ihrem Interesse runter.

\begin{enumerate}
\item Erstellen Sie eine R Shiny Web App aus den Daten.
\item Sie geben die R Shiny Web App als ZIP-Datei beinhaltend alle
  notwendigen Dateien um die App laufen zu lassen. 
\end{enumerate}

\subsection*{Zerforschung I}

\begin{enumerate}
\item Suchen Sie sich auf dem Campus Haste ein Poster und Fotografieren
  Sie eine der dortigen Abbildungen!
\item Erstellen Sie den Datensatz auf dem die Abbildung basieren k{\"o}nnte!
  Sch{\"a}tzen Sie daf{\"u}r grob die Zahlen aus der fotografierten Abbildung ab.
\item Bauen Sie aus den selbst erstellten Daten die fotografierte Abbildung in
  \texttt{ggplot()} nach!
\item Geben Sie den Code und die Abbildung in R Quarto ab!
\end{enumerate}

\subsection*{Zerforschung II}

\begin{enumerate}
\item Begeben Sie sich in die Bibliothek in Haste. Suchen Sie sich drei
  Abschlussarbeiten aus.
\item Erstellen Sie eine deskriptive {\"U}bersicht {\"u}ber den Umfang der drei
  Abschlussarbeiten!
\item Sehen Sie folgende Fragen als Inspiration. Wie viele Referenzen
  finden Sie? Welche Art sind die Referenzen? Wie lang ist die Einleitung?
  Wie viele Abschnitte haben die einzelnen Teile? Welche statistischen
  Tests werden verwendet? Welche Abschnitte gibt es {\"u}berhaupt? Wie viele
  Referenzen stammen von dem Betreuenden?
\item Fasse Sie Ihre {\"U}bersicht in maximal drei Seiten zusammen.
\end{enumerate}

\subsection*{Erforschen \& Erkunden}

Besuchen Sie den Hasefriedhof oder den Johannisfriedhof in
Osnabr{\"u}ck. Finden Sie eine Pers{\"o}nlichkeit, die dort ruht und
inspiriert. Die Pers{\"o}nlichkeit sollte im weitesten Sinne eine Verbindung zur
Wissenschaft haben. Anfang des letzten Jahrhunderts ist die Trennung der
Disziplinen aber sehr unscharf.

\begin{enumerate}
\item Machen Sie ein Foto von der Grabst{\"a}tte!
\item F{\"u}gen Sie das Foto in ein Dokument ein und schreiben Sie ein bis zwei
  Seiten {\"u}ber die Pers{\"o}nlichkeit und deren wissenschaftliches Wirken!
\item Warum haben Sie diese Pers{\"o}nlichkeit gew{\"a}hlt?
\end{enumerate}

\subsection*{Reflexion}

Besuchen Sie die Internetseite https://www.bigbookofr.com/ und w{\"a}hlen Sie
eines der {\"u}ber 300 B{\"u}cher aus.

\begin{enumerate}
\item Schreiben Sie eine zweiseitige Zusammenfassung {\"u}ber das Buch!
\end{enumerate}




\end{document}
