---
title: "Spezielle Statistik und Versuchswesen"
subtitle: "Portfolioprüfung"
author: "Jochen Kruppa-Scheetz"
date: "SoSe 2024"
format: 
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
---

Im Folgenden finden Sie die notwendigen Informationen zu der Portfolioprüfung für das Modul "Spezielle Statistik und Versuchswesen". *Die einzelnen Aufgaben der Portfolioprüfung sind voneinander unabhängig.* Die Portfolioprüfung wird gesammelt abgegeben und nachträgliche Ergänzungen sind nicht mehr möglich. Die Abgabe kann grundsätzlich auch im Laufe des Semesters erfolgen. Der Stichtag findet sich am Ende des Dokuments.

## Datenanalyse in R (verpflichtend)

### Formalia

-   Ihr Bericht folgt dem IMRaD Schema und ist acht bis *maximal* zehn Seiten lang.
-   Ihr Bericht beinhaltet zwischen fünf und zehn wissenschaftliche Referenzen. 
-   Die Datenanalyse und die Erstellung des Berichts findet in *R Quatro* statt. **(+1 Punkt)**

### Daten

-   Wählen Sie einen agrarwissenschaftlichen Datensatz aus dem R Paket `{agridat}`. Eine gute Übersicht finden Sie auch unter <https://kwstat.github.io/agridat/reference/>.

### Inhalte der Auswertung

-   Entwickeln Sie anhand der ausgewählten Daten eine Fragestellung!
-   Nutzen Sie das Tool ChatGPT/HAWKI  um die Einleitung zu schreiben. Geben Sie am Ende der Einleitung eine tabellarische Übersicht der Fragen an ChatGPT/HAWKI!
-   Zeichen Sie mit den gegebenen Informationen den Versuchsplan. Welche Annahmen haben Sie getroffen? Erläutern Sie Ihr Vorgehen.
-   Visualisieren Sie Ihre Daten in `{ggplot}` im Kontext der Fragestellung!
-   Rechen Sie die statistische Analyse in R entsprechend Ihres Endpunktes! 
-   Diskutieren Sie Ihre Ergebnisse im Kontext der Fragestellung und möglicher Komplikationen! Nutzen Sie auch hier das Tool ChatGPT/HAWKI. Geben Sie am Ende der Diskussion eine tabellarische Übersicht der Fragen an ChatGPT!

## R Shiny Web App (optional)

Besuchen Sie die Internetseite <https://ourworldindata.org/> oder <https://www.fao.org/faostat/> und laden sich einen Datensatz von Ihrem Interesse runter. Sie dürfen den Datensatz beliebig vorab kürzen oder bearbeiten, so dass Sie die Aufgabe gut lösen können.

-   Überlegen Sie sich eine Fragestellung zu den Daten.
-   Erstellen Sie eine R Shiny Web App aus den Daten, die bei der Beantwortung der Fragestellung hilfreich ist.
-   Sie geben die R Shiny Web App als ZIP-Datei ab. Die ZIP-Datei beinhaltend alle notwendigen Dateien um die App laufen zu lassen.

## Präsentation (optional, nur im WiSe möglich!)

Was haben Sie in der Portfolioprüfung gemacht, was Sie besonders spannend oder herausfordernd fanden? Stellen Sie es doch uns allen einmal vor!

- Sie stellen in Ihrer Präsentation einen selbstgewählten Teil der Portfoliopfüfung vor. 
- Sie sind frei in dem Vortrag, der Form und dem Inhalt.
- Sie erstellen die Präsentation in *R Quatro*. **(+ 1 Punkt)**

*Die Präsentation ist nur am Ende der regulären Vorlesung im WiSe im Januar möglich.* 

## Zerforschung I (verpflichtend)

Suchen Sie sich auf dem Campus Haste ein wissenschaftliches Poster und Fotografieren Sie eine der dortigen statistischen Abbildungen!

-   Erstellen Sie den Datensatz auf dem die Abbildung basieren könnte! Schätzen Sie dafür grob die Zahlen aus der fotografierten Abbildung ab.
-   Bauen Sie aus den selbst erstellten Daten die fotografierte Abbildung in `ggplot()` nach!
-   Geben Sie den Code und die Abbildung in einem R Quarto erstellten Dokument ab!

## Zerforschung II (verpflichtend)

Begeben Sie sich in die Bibliothek in Haste. Suchen Sie sich drei Abschlussarbeiten aus. Welche Sie wählen ist Ihnen überlassen.

-   Erstellen Sie eine deskriptive Übersicht über den Umfang der drei Abschlussarbeiten!
-   *Sehen Sie folgende Fragen als Inspiration.* Wie viele Seiten haben die Arbeiten? Wie viele Referenzen finden Sie? Welche Art sind die Referenzen? Wie lang ist die Einleitung? Wie viele Abschnitte haben die einzelnen Teile? Welche statistischen Tests werden verwendet? Welche Abschnitte gibt es überhaupt? Wie viele Referenzen stammen von dem Betreuenden?
-   Fassen Sie Ihre Übersicht in maximal drei Seiten zusammen.

## Zerforschung III (verpflichtend)

Wählen Sie eine Kurzbeschreibung eines Forschungsvorhaben aus der Datei *Forschungsideen.pdf* aus.

-   Erstellen Sie eine Exceldatei entsprechend der Kurzbeschreibung! Sie wollen nach dem Versuch die erstellte Exceldatei dann mit den Messdaten füllen. Beachten Sie, dass Sie Wiederholungen benötigen. Legen Sie die Anzahl an Wiederholungen selbstständig fest. Die Exceldatei muss in R einlesbar sein.
-   Erstellen Sie eine Randomisierung und Visualisierung des experimentellen Versuchsdesign anhand der Kurzbeschreibung! Sie können die Randomisierung in PowerPoint oder `{desplot}` visualisieren.

## Erforschen & Erkunden (optional)

Machen Sie eine Exkursion. Dabie haben Sie drei Möglichkeiten zur Auswahl:

1) Besuchen Sie den Hasefriedhof *oder* den Johannisfriedhof in Osnabrück.
2) Besuchen Sie das Haus der NaturKultur (Am Markt 35, 49565 Bramsche). **(+1 Punkt)**
3) Machen Sie eine eigenverantwortliche Exkursion, die zu folgenden Teilaufgaben passt. **(+2 Punkte)**

Finden Sie eine Persönlichkeit in Ihrer Exkursion, die Sie inspiriert. Die Persönlichkeit sollte im weitesten Sinne eine Verbindung zur Wissenschaft haben. Anfang des letzten Jahrhunderts ist die Trennung der Disziplinen aber sehr unscharf, so dass je nach Exkursion der Begriff "Wissenschaft" weit gefasst ist.

-   Machen Sie ein aussagekräftiges Foto von einem Objekt Ihrer Exkursion!
-   Fügen Sie das Foto in ein Dokument ein!
-   Warum haben Sie dieses Objekt gewählt? Was hat Sie inspiriert? 
-   Reflektieren Sie ein bis zwei Seiten über die Persönlichkeit und deren wissenschaftliches Wirken im Kontext Ihrer eigenen (familiären) Erfahrungen! 

## Reflexion (optional)

Besuchen Sie die Internetseite <https://www.bigbookofr.com/> und wählen Sie eines der über 300 Bücher aus. Sie dürfen jedes Thema nehmen was Sie interessiert. Nehmen Sie aber ein *Buch*, keine verlinkte Internetseite oder Blogartikel.

-   Schreiben Sie eine maximal zweiseitige Zusammenfassung über das Buch!
-   Warum haben Sie dieses Buch gewählt?

## Benotung

Im Folgenden ist die Tabelle für die Benotung angegeben. Es können maximal 20 Punkte erreicht werden. Um das Modul zu bestehen benötigen Sie mindestens 11 Punkte. Themen mit Teilpunkten in (Klammern) stellen optinal erreichbare Bonuspunkte in den jeweiligen Aufgaben dar. Themen mit Teilpunkten, die in **[fett]** gedruckt sind, müssen *mindestens* erreicht werden. 

| Thema                 | Teilpunkte    | 
|-----------------------|---------------|
| Datenanalyse in R     | 0, **[1]**, 2, 3, 4, (5) |      
| R Shiny Web App       | 0, 1, 2  |       
| Präsentation          | 0, 1, (2)          |      
| Zerforschung I        | 0, **[1]**, 2, 3, 4 |      
| Zerforschung II       | 0, **[1]**, 2       |        
| Zerforschung III      | 0, **[1]**, 2, 3, 4 |       
| Erforschen & Erkunden | 0, 1, (2), (3)       |       
| Reflexion             | 0, 1, 2       |        

**Die Abgabe ist digital jederzeit möglich, spätestens zum 31. Januar 2025.**
