---
title: "Modulpfad Spezielle Statistik und Versuchswesen"
subtitle: "Der folgende Pfad strukturiert das Modul und dient Ihnen als Leitfaden zur besseren Orientierung."
author: "Jochen Kruppa-Scheetz"
date: "22. September 2025"
format:
  html:
    embed-resources: true
    lang: de
    theme: journal
  pdf:
    colorlinks: true
---

Alle notwendigen zusätzlichen Informationen zum Modul finden Sie auf ILIAS, einschließlich:

-   Mitschriften der Vorlesung und der Übungen
-   R-Skripte und die in der Vorlesung verwendeten Dateien
-   Informationen zu der Prüfungsleistung der Portfolioprüfung

Beachten Sie bitte auch die zusätzlichen Informationen zu einzelnen Terminen auf ILIAS. 

### Skript als Lernhilfe

Das Openbook *Bio Data Science* dient als Skript der Veranstaltung und ist online unter <https://jkruppa.github.io/> verfügbar. Dort finden Sie ergänzend weiterführende Informationen zu R, Excel und der Datenauswertung. 

### Videos als Lernhilfe

Ergänzend zum Openbook *Bio Data Science* und den Veranstaltungsmitschriften stehen Ihnen unterstützende Lernvideos zur Veranstaltung auf YouTube unter <https://www.youtube.com/c/JochenKruppa> zur Verfügung. Dort finden Sie thematisch sortierte Playlists zu R- und Excel-Analysen sowie allgemeine Statistik-Videos.

#### Inhalt der Vorlesung

Nachfolgend finden Sie eine Übersicht der Modulinhalte. Die Weblinks führen Sie zu den entsprechenden Kapiteln im Openbook *Bio Data Science*. 

1) [Visualisierung von Daten](https://jkruppa.github.io/eda-ggplot.html)
2) [Forschungsprozess](https://jkruppa.github.io/forschungsprozess.html)
3) [Quarto und Shiny App](https://jkruppa.github.io/programing-quarto-shiny.html)
4) [Statistische Gruppenvergleiche](https://jkruppa.github.io/stat-tests-preface-app.html)
5) [Der Pre-Test oder Vortest](https://jkruppa.github.io/stat-tests-pretest2.html)
6) [Der Post-hoc Test](https://jkruppa.github.io/stat-tests-posthoc2.html)
7) [Experimentelle Designs](https://jkruppa.github.io/experimental-design-preface.html)
8) [Grundlagen des Modellierens](https://jkruppa.github.io/stat-linear-reg-preface.html)
9) [Zeitliche und räumliche Analysen](https://jkruppa.github.io/time-space-preface.html)
10) [Klassifikation oder maschinelles Lernen](https://jkruppa.github.io/classification-preface.html)

### Programmieren in R

Zum Verständnis der Programmierung in R stehen Ihnen das Openbook *Bio Data Science* und YouTube-Videos unter <https://www.youtube.com/c/JochenKruppa> zur Verfügung.

::: {.callout-note icon="false"}
## Aktive Teilnahme

- Programmieren in R ist integraler Bestandteil der Veranstaltung.
- Die Portfolioprüfung erfordert die selbstständige Anwendung von R.
:::

### Prüfungsleistung

Die Prüfungsleistung ist eine Portfolioprüfung. Alle weiteren Informationen dazu, einschließlich Abgabefristen und Inhalte, finden Sie im zusätzlichen Dokument auf ILIAS.

