---
title: "Spezielle Statistik und Versuchswesen"
subtitle: "Portfolioprüfung"
author: "Jochen Kruppa-Scheetz"
date: "23. August 2024"
format:
  html:
    embed-resources: true
    lang: de
---

Alle relevanten Informationen zur Portfolioprüfung für das Modul *"Spezielle Statistik und Versuchswesen"* sind nachfolgend aufgeführt. Die Abgabe ist im Laufe des Semesters jederzeit möglich.  

::: {.callout-note icon=false}
## Abgabe der Portfolioprüfung als PDF-Dateien oder ZIP-Ordner
Für die Abgabe gehen Sie bitte wie folgt vor:

1) Laden Sie Ihre PDF-Dateien oder als ZIP-Ordner in den ILIAS-Abgabeordner hoch.
2) Benennen Sie die Datei mit Ihrem Namen und Ihrer Matrikelnummer.
3) Die Abgabe muss bis zum **31. Januar 2025** erfolgen.
:::

## Datenanalyse in R (verpflichtend)

::: {.callout-note icon=false}
## Formalia
Für Ihren Bericht gelten folgende Anforderungen:

1) Der Bericht ist im IMRaD-Schema zu verfassen.
2) Der Umfang beträgt 8 bis maximal 10 Seiten reinen Fließtextes. Aufzählungen sind nicht zulässig.
3) Die Datenanalyse ist mit der Software RStudio und R durchzuführen.
4) Sie erstellen Ihren Bereicht in *R Quatro*. **(+1 Punkt)** 
:::

Für Ihre Analyse wählen Sie bitte einen agrarwissenschaftlichen Datensatz aus dem R Paket {agridat} aus. Beachten Sie, dass der Datensatz auf einem faktoriellen Versuchsdesign basieren muss. Eine gute Übersicht finden Sie auch unter <https://kwstat.github.io/agridat/reference/>.

Ihre Datenanalyse wird nach folgenden Kriterien bewertet:

- **Einleitung (1 Punkt):** Entwicklung einer wissenschaftlichen Fragestellung auf Basis der ausgewählten Daten.
- **Materialien und Methoden (1 Punkt):**
  - Beschreibung des Versuchsplans anhand der gegebenen Informationen.
  - Beschreibung der angewandten statistischen Methoden zur Datenauswertung.
- **Ergebnisse (2 Punkte):**
  - Visualisierung der Daten in {ggplot} im Kontext der Fragestellung.
  - Bericht der Ergebnisse und Erkenntnisse aus der statistischen Analyse.
- **Diskussion (1 Punkt):** Bewertung der Ergebnisse im Kontext der Fragestellung.


## Zerforschung I (verpflichtend)

Suchen Sie sich auf dem Campus Haste ein wissenschaftliches Poster und Fotografieren Sie eine der dortigen statistischen Abbildungen!

-   Erstellen Sie den Datensatz auf dem die Abbildung basieren könnte! Schätzen Sie dafür grob die Zahlen aus der fotografierten Abbildung ab.
-   Bauen Sie aus den selbst erstellten Daten die fotografierte Abbildung in `{ggplot}` nach!
-   Geben Sie den Code und die Abbildung in einem R Quarto erstellten Dokument ab!

## Zerforschung II (verpflichtend)

Begeben Sie sich in die Bibliothek in Haste. Suchen Sie sich drei Abschlussarbeiten aus. Welche Sie wählen ist Ihnen überlassen.

-   Erstellen Sie eine deskriptive Übersicht über den Umfang der drei Abschlussarbeiten!
-   *Sehen Sie folgende Fragen als Inspiration.* Wie viele Seiten haben die Arbeiten? Wie viele Referenzen finden Sie? Welche Art sind die Referenzen? Wie lang ist die Einleitung? Wie viele Abschnitte haben die einzelnen Teile? Welche statistischen Tests werden verwendet? Welche Abschnitte gibt es überhaupt? Wie viele Referenzen stammen von dem Betreuenden?
-   Fassen Sie Ihre Übersicht in maximal drei Seiten zusammen.

## Zerforschung III (verpflichtend)

Wählen Sie eine Kurzbeschreibung eines Forschungsvorhaben aus der Datei *Forschungsideen.pdf* aus.

-   Erstellen Sie eine Exceldatei entsprechend der Kurzbeschreibung! Sie wollen nach dem Versuch die erstellte Exceldatei dann mit den Messdaten füllen. Beachten Sie, dass Sie Wiederholungen benötigen. Legen Sie die Anzahl an Wiederholungen selbstständig fest. Die Exceldatei muss in R einlesbar sein.
-   Erstellen Sie eine Randomisierung und Visualisierung des experimentellen Versuchsdesign anhand der Kurzbeschreibung! Sie können die Randomisierung in PowerPoint oder `{desplot}` visualisieren.

## R Shiny Web App (optional)

::: {.callout-note icon=false}
## Formalia
Für Ihre R Shiny Web App gelten folgende Anforderungen:

1) Sie geben die R Shiny Web App als ZIP-Datei ab.
2) Die ZIP-Datei beinhaltend alle notwendigen Dateien um die App laufen zu lassen.
:::

Besuchen Sie die Internetseite <https://ourworldindata.org/> oder <https://www.fao.org/faostat/> und laden sich einen Datensatz von Ihrem Interesse runter. Sie dürfen den Datensatz beliebig vorab kürzen oder bearbeiten, so dass Sie die Aufgabe gut lösen können.

-   Überlegen Sie sich eine Fragestellung zu den Daten.
-   Erstellen Sie eine R Shiny Web App aus den Daten, die bei der Beantwortung der Fragestellung hilfreich ist.

## Präsentation (optional, nur im Wintersemester)

::: {.callout-note icon=false}
## Formalia
Für Ihre Präsentation gelten folgende Anforderungen:

1) Die Präsentationen finden ausschließlich am Ende der regulären Vorlesungszeit im Wintersemester (Januar) statt.
2) Inhalt, Form und Vortragsstil der Präsentation sind frei wählbar.
3) Sie erstellen die Präsentation in *R Quatro*. **(+1 Punkt)**
:::

Wählen Sie einen Aspekt Ihrer Portfolioprüfung aus und stellen Sie ihn in einer Präsentation vor. Beschreiben Sie, welche Aufgaben Sie bearbeitet haben, welche Herausforderungen Sie gemeistert haben und welche Lernerfahrungen Sie daraus gezogen haben.

## Erforschen & Erkunden (optional)

::: {.callout-note icon=false}
## Formalia
Für Ihre Exkursion gelten folgende Anforderungen:

1) Wählen Sie für Ihre Exkursion entweder den Hasefriedhof oder den Johannisfriedhof in Osnabrück.
2) Führen Sie eine eigenverantwortliche Exkursion durch, die sich auf die folgenden Teilaufgaben bezieht. **(+1 Punkt)**
3) Erstellen Sie ein aussagekräftiges Foto von einem Objekt Ihrer Exkursion und fügen Sie dieses in Ihr Dokument ein.
:::

Entdecken Sie während Ihrer Exkursion eine Persönlichkeit, deren Leben und Werk Sie inspiriert. Diese Person sollte im weitesten Sinne einen Bezug zur Wissenschaft haben. Beachten Sie, dass die Grenzen zwischen den Disziplinen zu Beginn des 20. Jahrhunderts oft fließend waren, daher ist der Begriff *"Wissenschaft"* hier weit gefasst.

Verfassen Sie eine Reflexion von ein bis zwei Seiten, in der Sie diese Persönlichkeit und ihr wissenschaftliches Wirken im Kontext Ihrer eigenen (familiären) Erfahrungen betrachten.

## Reflexion (optional)

::: {.callout-note icon=false}
## Formalia
Für Ihre Reflexion gelten folgende Anforderungen:

1) Verfassen Sie eine Zusammenfassung des Buches im Umfang von maximal zwei Seiten.
2)Erläutern Sie, warum Sie sich für dieses Buch entschieden haben.
:::

Besuchen Sie die Webseite <https://www.bigbookofr.com/> und wählen Sie ein Buch aus den über 300 verfügbaren Titeln aus. Das Thema ist frei wählbar. Bitte beachten Sie, dass ausschließlich Bücher für diese Aufgabe zugelassen sind, keine verlinkten Webseiten oder Blogartikel.

## Benotung

Die folgende Tabelle zeigt die Benotungsgrundlage für dieses Modul. Es können maximal 20 Punkte erreicht werden. Zum Bestehen des Moduls sind mindestens 11 Punkte erforderlich.

- **Bonuspunkte:** Aufgaben mit Teilpunkten in *kursiven Klammern ( )* bieten die Möglichkeit, zusätzliche Bonuspunkte zu erlangen.
- **Mindestpunktzahl:** Aufgaben mit Teilpunkten in **fettgedruckten Klammern [ ]** müssen mindestens erreicht werden."

| Thema                 | Teilpunkte    | 
|-----------------------|---------------|
| Datenanalyse in R     | 0, **[1]**, 2, 3, 4, 5, *(6)* |      
| R Shiny Web App       | 0, 1, 2, 3  |       
| Präsentation          | 0, 1, *(2)*         |      
| Zerforschung I        | 0, **[1]**, 2, 3, 4, 5 |      
| Zerforschung II       | 0, **[1]**, 2       |        
| Zerforschung III      | 0, **[1]**, 2, 3, 4, 5 |       
| Erforschen & Erkunden | 0, 1, *(2)*       |       
| Reflexion             | 0, 1       |        

