---
title: "Modulpfad Angewandte Statistik und Versuchswesen"
subtitle: "Der folgende Pfad strukturiert das Modul und dient Ihnen als Leitfaden zur besseren Orientierung."
author: "Jochen Kruppa-Scheetz"
date: "06. February 2026"
format:
  html:
    embed-resources: true
    lang: de
    theme: journal
  pdf:
    colorlinks: true
---

::: {.callout-note icon="false"}
## Gültigkeit 

Dieses Dokument ist für das **Sommersemester 2026** und das darauffolgende **Wintersemester 2026/27** gültig.
:::

Alle notwendigen zusätzlichen Informationen zum Modul finden Sie auf ILIAS, einschließlich:

-   Mitschriften der Vorlesung und der Übungen
-   R-Skripte und die in der Vorlesung verwendeten Dateien
-   Die gesammelten Klausurfragen für Bio Data Science

Beachten Sie bitte auch die zusätzlichen Informationen zu einzelnen Terminen auf ILIAS. 

### Skript als Lernhilfe

Das Openbook *Bio Data Science* dient als Skript der Veranstaltung und ist online unter <https://jkruppa.github.io/> verfügbar. Dort finden Sie ergänzend weiterführende Informationen zu R, Excel und der Datenauswertung. *Für die Klausur sind jedoch primär die Inhalte der Veranstaltungsmitschriften relevant.* Beachten Sie die Veranstaltungsmitschriften daher besonders.

### Videos als Lernhilfe

Ergänzend zum Openbook *Bio Data Science* und den Veranstaltungsmitschriften stehen Ihnen unterstützende Lernvideos zur Veranstaltung auf YouTube unter <https://www.youtube.com/c/JochenKruppa> zur Verfügung. Dort finden Sie thematisch sortierte Playlists zu R- und Excel-Analysen sowie allgemeine Statistik-Videos.

### Programmieren in R

Zum Verständnis der Programmierung in R stehen Ihnen das Openbook *Bio Data Science* und YouTube-Videos unter <https://www.youtube.com/c/JochenKruppa> zur Verfügung.

::: {.callout-note icon="false"}
## Aktive Teilnahme

- Programmieren in R ist integraler Bestandteil der Veranstaltung.
- Die optionale Hausarbeit erfordert die selbstständige Anwendung von R.
- Theoretische R-Kenntnisse sind klausurrelevant.
:::

### Inhalt der Vorlesung

Nachfolgend finden Sie eine Übersicht der Modulinhalte. Die Weblinks führen Sie zu den entsprechenden YouTube-Videos. Alle Inhalte sind verbindlich für die Klausur, auch wenn einzelne Vorlesungen krankheitsbedingt ausfallen sollten. Eine umfassende Übersicht über die Modulinhalte bietet Ihnen die [YouTube-Playlist Openbook *Bio Data Sciene*](https://www.youtube.com/watch?v=2stKP2iLGYY&list=PLe51bCp9JvEHAD63zTDE_jS3HNYuG6BrB). Diese Videos sind als Ergänzung und zur Wiederholung konzipiert. Insbesondere folgende Inhalte aus dem Openbook *Bio Data Science* sind prüfungsrelevant:

1) [Programmieren in R](https://jkruppa.github.io/programing-preface.html)
2) [Deskriptive Statistik](https://jkruppa.github.io/eda-descriptive.html)
3) [Visualisierung von Daten](https://jkruppa.github.io/eda-ggplot.html)
4) [Die Testentscheidung](https://jkruppa.github.io/stat-tests-basic.html)
5) [Die Testtheorie](https://jkruppa.github.io/stat-tests-theorie.html)
6) [Der t-Test](https://jkruppa.github.io/stat-tests-ttest.html)
7) [Die ANOVA](https://jkruppa.github.io/stat-tests-anova2.html)
8) [Der Chi-Quadrat-Test](https://jkruppa.github.io/stat-tests-chi-test.html)

### Prüfungsleistung

Die Prüfungsleistung umfasst eine schriftliche Klausur und optional eine Hausarbeit. Für beide werden Punkte vergeben. Zum Bestehen ist das Gesamtergebnis entscheidend, nicht das Ergebnis einzelner Teilleistungen. Die Teilnahme an der schriftlichen Klausur ist verbindlich. Die Abgabe der Hausarbeit ist freiwillig. 

Die Prüfungsphase ist im Wintersemester im Januar und im Sommersemester im Juni. Den Prüfungsplan für das laufende Semester finden Sie im Intranet der Hochschule Osnabrück unter <https://intranet.hs-osnabrueck.de/infothek/fakultaet-aul/studium/pruefungen/>. 

::: {.callout-note icon="false"}
## Schriftliche Klausur

Auf ILIAS finden Sie eine PDF-Datei mit allen potenziellen Klausurfragen des Moduls. Zu fast allen Aufgaben sind erklärende YouTube-Videos verlinkt. 

**Die schriftliche Klausur gliedert sich in:**

-   *Multiple-Choice-Teil:* 10 Aufgaben (5 Antwortmöglichkeiten pro Frage, davon 1 richtig). Falsche Antworten führen zu keinem Punktabzug.
-   *Text- und Rechenteil:* 6 Aufgaben. 

**Erlaubte Hilfsmittel:**

-   Taschenrechner (nicht kommunikationsfähig, kein Handy!).
-   Eine beidseitig handschriftlich beschriebene DIN A4-Formelsammlung (keine Ausdrucke).

**Bearbeitungszeit:** 120 Minuten (2 Stunden).
:::

#### Inhalt der Klausur

Die Klausurinhalte werden jedes Wintersemester aktualisiert. Aus diesem Grund beziehen sich die hier bereitgestellten Aufgaben ausschließlich auf die Hauptklausur des Wintersemesters und die Nachklausur des darauffolgenden Sommersemesters. Für Wiederholungsprüfungen in folgenden Jahren ist es entscheidend, den jeweils aktuellen Stoff zu beachten.

*Es werden sechs der folgenden Statistikaufgaben in der Klausur drankommen.*

1) [Grundlegende Kenntnisse der Programierung in R](https://www.youtube.com/playlist?list=PLe51bCp9JvEFUnFqaJG5aRmON9i1ZbOYC)
2) [Zerforschen des Barplots](https://youtu.be/GNoORO7GfAE) 
3) [Visualisierung des Barplots](https://youtu.be/UabXe73G-7w) 
4) [Zerforschen des Boxplots](https://youtu.be/MyrNZ46i3uY) 
5) [Visualisierung des Boxplots](https://youtu.be/ZbrvpCuZl_k)
6) [Visualisierung des Scatterplots](https://youtu.be/md9I_UV5_lE) 
7) [Visualisierung des Mosaicplots](https://youtu.be/L4nSytEHcaE) 
8) [Grundgesamtheit und experimentelle Stichprobe](https://youtu.be/KxDklbFEEHw) 
9) [Das Nullritual - Die statistische Testtheorie](https://youtu.be/XAE8BwNmCQ0) 
10) [Visualisierung der Teststatistik und dem p-Wert](https://youtu.be/2LQzyQCy2FI) 
11) [Berechnung des Student t-Test oder Welch t-Test](https://youtu.be/zgpw9GC0plk) 
12) [Berechnung des Student t-Test](https://youtu.be/eGoLNgE-WCo) 
13) [Interpretation des t-Tests in  R: Teststatistik und p-Wert](https://youtu.be/K3LGigegKIg) 
14) [Interpretation des t-Tests in  R: die Visualisierung](https://youtu.be/02hibcRs5Wc) 
15) [Berechnung des gepaarten t-Test](https://youtu.be/QR90zyn0Iz8)
16) [Interpretation des gepaarten t-Tests in R](https://youtu.be/kHmfEmU6lrk)
17) [Visualisierung der einfaktoriellen ANOVA](https://youtu.be/wEePzcwwti8)
18) [Ergebnistabelle der einfaktoriellen ANOVA](https://youtu.be/25bvWshX-Gw) 
19) [Die einfaktorielle ANOVA in R](https://youtu.be/UOzpeBYWgVQ)
20) [Den Chi-Quadrat-Test berechnen](https://youtu.be/1y_X_TI-Gm4) 
21) [Den Chi-Quadrat-Test mit Effektmaß berechnen](https://youtu.be/IcjUIoEo0rY) 
22) [Den Chi-Quadrat-Test in einem Fragebogen berechnen](https://youtu.be/LzAAdJPH4ZU) 

#### Hausarbeit

Alle relevanten Informationen zur Hausarbeit für das Modul *"Angewandte Statistik und Versuchswesen"* sind nachfolgend aufgeführt. Die Abgabe ist im Laufe des Semesters jederzeit möglich.

Die Abgabe der Hausarbeit ist für das Bestehen des Moduls *"Angewandte Statistik und Versuchswesen"* nicht erforderlich.

::: {.callout-note icon="false"}
## Abgabe der Hausarbeit als PDF-Datei

Für die Abgabe gehen Sie bitte wie folgt vor:

1)  Laden Sie Ihre PDF-Datei in den ILIAS-Abgabeordner hoch.
2)  Benennen Sie die Datei mit Ihrem Namen und Ihrer Matrikelnummer.
3)  Die Abgabe muss bis zum **24. Mai 2026** erfolgen.
:::

##### Datenanalyse in R

Die Datenanalyse ist eine Gruppenarbeit. Die Gruppenarbeit beschränkt sich dabei auf die Erstellung der Daten und die Analyse der Hausarbeit. Die finale Abgabe des Textes muss von jedem Einzelnen persönlich erfolgen.

::: {.callout-note icon="false"}
## Formalia

Für Ihre Hausarbeit gelten folgende Anforderungen:

1)  Die Hausarbeit ist im IMRaD-Schema zu verfassen.
2)  Die Hausarbeit ist in **englischer Sprache** zu verfassen. 
2)  Der Umfang beträgt 8 bis maximal 10 Seiten reinen Fließtextes. Aufzählungen sind nicht zulässig.
3)  Die Datenanalyse ist mit der Software RStudio und R durchzuführen.
:::

Im Modul *"Angewandte Statistik und Versuchswesen"* entwickeln Sie in Zweiergruppen eine individuelle wissenschaftliche Fragestellung. Sie wählen die passenden Daten, führen die statistische Analyse eigenständig in R durch und stellen Ihre Erkenntnisse im Rahmen einer abschließenden Präsentation vor.

Ihre Hausarbeit wird nach folgenden Kriterien bewertet:

-   **Einleitung (2 Punkte):** Entwicklung einer wissenschaftlichen Fragestellung auf Basis der ausgewählten Daten.
-   **Materialien und Methoden (2 Punkte):**
    -   Beschreibung des Datensatzes anhand der gegebenen Informationen.
    -   Beschreibung der angewandten statistischen Methoden zur Datenauswertung.
-   **Ergebnisse (4 Punkte):**
    -   Visualisierung der Daten im Kontext der Fragestellung **(2 Punkte)**.
    -   Bericht der Ergebnisse und Erkenntnisse aus der statistischen Analyse **(2 Punkte)**.
-   **Diskussion (2 Punkte):** Bewertung der Ergebnisse im Kontext der Fragestellung.

##### Benotung

Ihre Leistung im Bericht und der Datenauswertung wird mit bis zu 10 Punkten bewertet. Diese Punkte fließen direkt in Ihre Gesamtnote ein, indem sie zu Ihrer Klausurpunktzahl addiert werden. Die erreichte Summe bestimmt dann Ihre endgültige Modulnote.
